=== Pedromemoire/gform-data-generator/schemas/form.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Locale": {
      "type": "string",
      "enum": [
        "ar",
        "az",
        "cz",
        "de",
        "de_AT",
        "de_CH",
        "en",
        "en_AU",
        "en_AU_ocker",
        "en_BORK",
        "en_CA",
        "en_GB",
        "en_IE",
        "en_IND",
        "en_US",
        "en_ZA",
        "es",
        "es_MX",
        "fa",
        "fi",
        "fr",
        "fr_CA",
        "fr_CH",
        "ge",
        "hr",
        "hy",
        "id_ID",
        "it",
        "ja",
        "ko",
        "nb_NO",
        "ne",
        "nl",
        "nl_BE",
        "pl",
        "pt_BR",
        "pt_PT",
        "ro",
        "ru",
        "sk",
        "sv",
        "tr",
        "uk",
        "vi",
        "zh_CN",
        "zh_TW"
      ]
    },
    "QuestionType": {
      "type": "string",
      "enum": [
        "CHECKBOXES",
        "CHECKBOX_GRID",
        "DATE",
        "FREE_TEXT",
        "MULTIPLE_CHOICE",
        "MULTIPLE_CHOICE_GRID",
        "TIME"
      ]
    },
    "AnswerOptionType": { "type": "string", "enum": [ "FIXED", "OTHER" ] }
  },
  "type": "object",
  "properties": {
    "title": { "type": "string" },
    "locale": { "$ref": "#/definitions/Locale" },
    "dateMin": { "type": "number", "minimum": 0 },
    "dateMax": { "type": "number", "minimum": 0 },
    "answerCount": { "type": "number", "minimum": 0 },
    "questions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": { "type": "string" },
          "type": { "$ref": "#/definitions/QuestionType" },
          "required": { "type": "boolean" }
        },
        "required": [ "title", "type", "required" ],
        "allOf": [
          {
            "if": {
              "properties": {
                "required": { "const": false },
                "type": {
                  "type": "string",
                  "enum": [
                    "CHECKBOXES",
                    "DATE",
                    "FREE_TEXT",
                    "MULTIPLE_CHOICE",
                    "TIME"
                  ]
                }
              },
              "required": [ "required", "type" ]
            },
            "then": {
              "properties": {
                "noAnswerProbability": { "type": "number", "minimum": 0, "maximum": 1 }
              },
              "required": [ "noAnswerProbability" ]
            }
          },
          {
            "if": {
              "properties": {
                "type": { "const": "FREE_TEXT" }
              },
              "required": [ "type" ]
            },
            "then": {
              "properties": {
                "answerModel": { "type": "string" }
              },
              "required": [ "answerModel" ]
            }
          },
          {
            "if": {
              "properties": {
                "type": { "type": "string", "const": "DATE" }
              },
              "required": [ "type" ]
            },
            "then": {
              "properties": {
                "min": { "type": "number", "minimum": 0 },
                "max": { "type": "number", "minimum": 0 },
                "withYear": { "type": "boolean" },
                "withTime": { "type": "boolean" }
              },
              "required": [ "min", "max", "withYear", "withTime" ]
            }
          },
          {
            "if": {
              "properties": {
                "type": { "const": "TIME" }
              },
              "required": [ "type" ]
            },
            "then": {
              "properties": {
                "min": { "type": "string", "pattern": "^([0-6][0-9]|7[0-2]):([0-5][0-9]):([0-5][0-9])$" },
                "max": { "type": "string", "pattern": "^([0-6][0-9]|7[0-2]):([0-5][0-9]):([0-5][0-9])$" }
              },
              "required": [ "min", "max" ]
            }
          },
          {
            "if": {
              "properties": {
                "type": { "type": "string", "enum": [ "MULTIPLE_CHOICE", "CHECKBOXES" ] }
              },
              "required": [ "type" ]
            },
            "then": {
              "properties": {
                "answerOptions": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "type": { "$ref": "#/definitions/AnswerOptionType" },
                      "probability": { "type": "number", "minimum": 0, "maximum": 1 }
                    },
                    "required": [ "type", "probability" ],
                    "allOf": [
                      {
                        "if": {
                          "properties": {
                            "type": { "type": "string", "const": "FIXED" }
                          },
                          "required": [ "type" ]
                        },
                        "then": {
                          "properties": {
                            "value": { "type": "string" }
                          },
                          "required": [ "value" ]
                        },
                        "else": {
                          "properties": {
                            "answerModel": { "type": "string" }
                          },
                          "required": [ "answerModel" ]
                        }
                      }
                    ]
                  }
                }
              },
              "required": [ "answerOptions" ]
            }
          },
          {
            "if": {
              "properties": {
                "type": { "type": "string", "enum": [ "MULTIPLE_CHOICE_GRID", "CHECKBOX_GRID" ] }
              },
              "required": [ "type" ]
            },
            "then": {
              "properties": {
                "columns": {
                  "type": "array",
                  "items": { "type": "string" }
                },
                "lines": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "title": { "type": "string" },
                      "probabilityGrid": {
                        "type": "array",
                        "items": { "type": "number", "minimum": 0, "maximum": 1 }
                      }
                    },
                    "required": [ "title", "probabilityGrid" ]
                  }
                }
              },
              "required": [ "columns", "lines" ],
              "if": {
                "properties": {
                  "required": { "const": false }
                },
                "required": [ "required" ]
              },
              "then": {
                "properties": {
                  "columns": {
                    "type": "array",
                    "items": { "type": "string" }
                  },
                  "lines": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "title": { "type": "string" },
                        "probabilityGrid": {
                          "type": "array",
                          "items": { "type": "number", "minimum": 0 }
                        },
                        "noAnswerProbability": { "type": "number", "minimum": 0, "maximum": 1 }
                      },
                      "required": [ "title", "probabilityGrid", "noAnswerProbability" ]
                    }
                  }
                },
                "required": [ "columns", "lines" ]
              }
            }
          }
        ]
      }
    }
  },
  "required": [
    "title",
    "locale",
    "dateMin",
    "dateMax",
    "answerCount",
    "questions"
  ]
}

=== Pedromemoire/gform-data-generator/forms/form.json
{
  "title": "Example Form",
  "locale": "en",
  "dateMin": 1609455600000,
  "dateMax": 1625090400000,
  "answerCount": 150,
  "questions": [
    {
      "title": "What is your email address ?",
      "type": "FREE_TEXT",
      "required": true,
      "answerModel": "{{internet.email}}"
    }, {
      "title": "What is your first name ?",
      "type": "FREE_TEXT",
      "required": true,
      "answerModel": "{{name.firstName}}"
    }, {
      "title": "Describe yourself in a few words",
      "type": "FREE_TEXT",
      "required": true,
      "answerModel": "{{name.jobTitle}} at {{name.jobArea}}"
    }, {
      "title": "Which type of music do you prefer ?",
      "type": "MULTIPLE_CHOICE",
      "required": true,
      "answerOptions": [
        {
          "type": "FIXED",
          "value": "Hard Rock",
          "probability": 0.6
        }, {
          "type": "FIXED",
          "value": "Metal",
          "probability": 0.2
        }, {
          "type": "FIXED",
          "value": "Rap",
          "probability": 0.1
        }, {
          "type": "OTHER",
          "answerModel": "{{music.genre}}",
          "probability": 0.1
        }
      ]
    }, {
      "title": "What is your gender ?",
      "type": "MULTIPLE_CHOICE",
      "required": false,
      "noAnswerProbability": 0.1,
      "answerOptions": [
        {
          "type": "FIXED",
          "value": "Male",
          "probability": 0.4
        }, {
          "type": "FIXED",
          "value": "Female",
          "probability": 0.3
        }, {
          "type": "OTHER",
          "answerModel": "{{name.gender}}",
          "probability": 0.3
        }
      ]
    }, {
      "title": "What is your birth date ?",
      "type": "DATE",
      "required": true,
      "withTime": false,
      "withYear": true,
      "min": 1609455600000,
      "max": 1625090400000
    }, {
      "title": "When was the first time you listened to your favorite artist ?",
      "type": "DATE",
      "required": true,
      "withTime": true,
      "withYear": true,
      "min": 1609455600000,
      "max": 1625090400000
    }, {
      "title": "When do you usually take your breakfast ?",
      "type": "TIME",
      "required": true,
      "min": "00:00:00",
      "max": "12:00:00"
    }, {
      "title": "How long does it usually take you to shower ?",
      "type": "TIME",
      "required": false,
      "noAnswerProbability": 0.5,
      "min": "20:00:00",
      "max": "50:00:00"
    }, {
      "title": "When do you usually take your breakfast ?",
      "type": "TIME",
      "required": true,
      "min": "05:00:50",
      "max": "19:30:50"
    }, {
      "title": "What do you like to do during your free time ?",
      "type": "CHECKBOXES",
      "required": true,
      "answerOptions": [
        {
          "type": "FIXED",
          "value": "Read books",
          "probability": 0.5
        }, {
          "type": "FIXED",
          "value": "Watch movies",
          "probability": 0.3
        }, {
          "type": "FIXED",
          "value": "Practice sports",
          "probability": 0.2
        }
      ]
    }, {
      "title": "What is your favorite activity throughout the day ?",
      "type": "MULTIPLE_CHOICE_GRID",
      "required": false,
      "lines": [
        {
          "title": "00h - 8h",
          "noAnswerProbability": 0.1,
          "probabilityGrid": [0.3, 0.2, 0.1, 0, 0.4]
        }, {
          "title": "8h - 12h",
          "noAnswerProbability": 0,
          "probabilityGrid": [0.5, 0.4, 0, 0, 0.1]
        }, {
          "title": "12h - 18h",
          "noAnswerProbability": 0.5,
          "probabilityGrid": [0, 0, 0.5, 0, 0.5]
        }, {
          "title": "18h - 00h",
          "noAnswerProbability": 0,
          "probabilityGrid": [0.3, 0.1, 0.2, 0.2, 0.2]
        }
      ],
      "columns": [
        "Sports",
        "Videogames",
        "Work",
        "Walking",
        "Reading Books"
      ]
    }, {
      "title": "What are your expectations ?",
      "type": "CHECKBOX_GRID",
      "required": true,
      "lines": [
        {
          "title": "Professional Life",
          "probabilityGrid": [0.4, 0.2, 0.1, 0.3]
        }, {
          "title": "Personal Life",
          "probabilityGrid": [0.2, 0.2, 0.5, 0.1]
        }
      ],
      "columns": [
        "Learning new skills",
        "Meeting new people",
        "Have fun with my friends",
        "Discover new places"
      ]
    }
  ]
}

=== Pedromemoire/gform-data-generator/memoire.json
{
  "title": "Mémoire Master 2 - Impact du stress sur l'intention de turnover chez les jeunes embauchés",
  "locale": "fr",
  "dateMin": 1609455600000,
  "dateMax": 1625090400000,
  "answerCount": 30,
  "questions": [
    {
      "title": "Le nombre de projets ou de missions que j'ai à réaliser.",
      "type": "CHECKBOXES",
      "required": true,
      "answerOptions": [
        {
          "type": "FIXED",
          "value": "1",
          "probability": 0.115
        }, {
          "type": "FIXED",
          "value": "2",
          "probability": 0.154
        }, {
          "type": "FIXED",
          "value": "3",
          "probability": 0.385
        }, {
          "type": "FIXED",
          "value": "4",
          "probability": 0.346
        }, {
          "type": "FIXED",
          "value": "5",
          "probability": 0
        }
      ]
    }
  ]
}
